@startuml
'https://plantuml.com/class-diagram

class Ex44_Main
{
+Scanner user_input
  {field}+ArrayList<String> name_arr
  +ArrayList<Integer> price_arr
  +ArrayList<Integer> quantity_arr
  +File input
  +JsonElement fileElement
  +JsonObject fileObject
  +JsonArray jsonArrayOfProducts
  +JsonObject productJsonObject

{method} +search_product()
{method} +main()

}


@enduml