@startuml
'https://plantuml.com/class-diagram

class Ex46_Main
{
  {field}+ArrayList<String> word_list
  +File input_file
  +BufferedReader br
  +String line
  +String full_text
  +ArrayList<String> key_words
  +String [] arr_split
  +ArrayList<Integer> key_word_count

{method} +find_frequency()
{method} +print_histogram()
{method} +main()

}

@enduml